# numpy.sort
numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)

In [5]:
import numpy as np
arr = np.array([[1, 9],[9, 8]])
print(arr)


np.sort(arr) #chon default axis = -1 hast pas dare row-wise sort mikoone

[[1 9]
 [9 8]]


array([[1, 9],
       [8, 9]])

In [6]:
#hala age begam axis = 0 miad sotooni sort mikone
np.sort(arr, axis=0)

array([[1, 8],
       [9, 9]])

In [9]:
#va oder ke dar halate default None hast vali be in manie ke man mitoonam yek seri vijegi ya key taarif konam va begam bar asase in feature sort kon yani masalan man mitoonam yek data e
#dashte basham ke mesle zir hast

#data = (name, ghad, vazn, sen)

#ke shamele name va ghad va vazn va sen hast va masalan migam bar asase ghad ya vazn ya sen sort kon ya tarkibi az chand feature sort kon

#yek mesal baraye order be shekle zir:
#avval yek dtype taarif mikonam va baad yek seri values taarif mikonam va ba estefade az numpy az in 2 ta yek arraye numpy misazam
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values= [("Ali", 1.8, 49), ("Hesam", 1.78, 29), ("reza", 1.7, 49)]
arr = np.array(values, dtype=dtype) #ba in kar yek array baram misazeh ke az type ndarray hast
arr

array([(b'Ali', 1.8 , 49), (b'Hesam', 1.78, 29), (b'reza', 1.7 , 49)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [10]:
#hala baraye sort kardane in ba tavajoh be order miam masalan avval ba tavajoh be height sort mikonam
np.sort(arr, order='height') #alan bar asase ghad sort kard

array([(b'reza', 1.7 , 49), (b'Hesam', 1.78, 29), (b'Ali', 1.8 , 49)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [15]:
np.sort(arr, order='age') #alan bar asase sen sort kard va ali va reza ke sene yeksani darand(49) ro aval ali ro ovord bad reza ro


array([(b'Hesam', 1.78, 29), (b'Ali', 1.8 , 49), (b'reza', 1.7 , 49)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [14]:
##hala mikham begam age sen yeksan bood avval ooni ro biar ke ghade kamtar dare
np.sort(arr, order=['age', 'height'])

array([(b'Hesam', 1.78, 29), (b'reza', 1.7 , 49), (b'Ali', 1.8 , 49)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

# numpy.lexsort
numpy.lexsort(keys, axis=-1) #return index of sorted array

In [20]:
arr_1 = [1, 5, 1, 4, 3, 4, 4]
arr_2 = [9, 4, 0, 4, 0, 2, 1]
np.lexsort((arr_1, arr_2)) #return index of sorted array

array([2, 4, 6, 5, 3, 1, 0])

In [21]:
#hala mitoonam eleman ha ya adadesh ro ham print konam
indices = np.lexsort((arr_1, arr_2))
[(arr_1[i], arr_2[i]) for i in indices]

[(1, 0), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4), (1, 9)]

In [26]:
###mitoonam ino alphabetically ham bokonam
first_names = ["Hesam", "Ali", "reza"]
last_names  = ["Zahra", "Hossein", "Hamed"]
indices = np.lexsort((first_names, last_names)) #inja migam last_names haro meyar gharar bede va sort kon
indices


array([2, 1, 0])

In [25]:
[(first_names[i] + " , " + last_names[i]) for i in indices]

['reza,Hamed', 'Ali,Hossein', 'Hesam,Zahra']

In [28]:
###ma dar bala conflict nadarim vali age conflict dashte bashim mesle zir mishe
first_names = ["Hesam", "Ali", "reza"]
last_names  = ["Zahra", "Hamed", "Hamed"]
indices = np.lexsort((first_names, last_names))
indices

array([1, 2, 0])

In [29]:
[(first_names[i] + " , " + last_names[i]) for i in indices] #inja chon 2 ta hamed yeksan daram miad avval ooni ro bar midare ke alphbetically koochaktar bashe ke mishe Ali

['Ali , Hamed', 'reza , Hamed', 'Hesam , Zahra']

In [ ]:
####pas lexsort miad va sortesh ro bar asase akharin eleman nesbat be avvalin eleman anjam mide yani masalan az last_names be first_names va age too last_names moshabeh bood miad az elemane avvalesh
#yani first_names estefadeh mikone va oon ke moghadam hast ro lahaz mikone


# numpy.argsort
numpy.argsort(a, axis=-1, kind=None, order=None, *, stable=None) #in ham mesle lexsort miad va index barmigardoone faghat farghi ke dare ine ke kind va order dare

In [30]:
arr = np.array([2, 0, 3, 6, 7, 1, 0, 2, 9])
out_arr = np.argsort(arr)
out_arr #ke mibinim andis haye adade koochak be bozorg ro bargardoonde

array([1, 6, 5, 0, 7, 2, 3, 4, 8])

In [31]:
###hala age oon andisha ke tooye out_arr rikhtim tooye original arraye gharar bedim khode adad haro ham behem neshoon mide
arr[out_arr]

array([0, 0, 1, 2, 2, 3, 6, 7, 9])

In [35]:
##hala yek arrayeye 2D taarif mikonam va ba argsort moratabesh mikonam
arr_2D = np.array([[3, 0, 2],[9, 7, 1]])
np.argsort(arr_2D, kind="mergesort", axis=0)

array([[0, 0, 1],
       [1, 1, 0]])

In [36]:
#hala hamoon mesale ghabli ba axis=1
arr_2D = np.array([[3, 0, 2],[9, 7, 1]])
np.argsort(arr_2D, kind="mergesort", axis=1)

array([[1, 2, 0],
       [2, 1, 0]])