# numpy.argmax
numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)
# numpy.nanargmax
numpy.nanargmax(a, axis=None, out=None, *, keepdims=<no value>)
# numpy.argmin
numpy.argmin(a, axis=None, out=None, *, keepdims=<no value>)
# numpy.nanargmin
numpy.nanargmin(a, axis=None, out=None, *, keepdims=<no value>)

In [ ]:
###argmax va argmin andise bozorgtarin va koochaktarin adad tooye arraye ro peyda  mikone
###ama kheyli vaghta ma missing value darim va meghdaresh ba nan por mishe va nan hamoon null hast va age man too arraye nan dashte basham va bekham max va min ro hesab konam ba moshkel movajeh misham
# va baraye hamin numpy behem method haye nanargmax va nanargmin ro mide vali in 2 nan
#haro ignore mikonan

In [79]:
import numpy as np ##avval yek data yi taarif mikonim
arr = np.random.randint(16, size=(4,4))
arr

array([[11,  1,  6,  2],
       [ 9,  8,  8, 14],
       [11, 12,  9,  0],
       [ 2,  6,  1,  1]])

In [12]:
np.argmax(arr) #vaghti ino estefadeh konam va axis ro dar nazar nagiram avval miad va matris ro flat mikone yani intori mishe [2, 5, 2, 2, 0, 12, 1, 8, 8, 15, 13, 6, 4, 14, 7, 6]
#va tooye inha 14 az hame bozorgtare ke mishe andise 9

np.int64(9)

In [13]:
np.argmax(arr, axis=0)
#hala age axis=0 bedam chi ??
#miad va tooye har sotoone matris andise bozorgtarin adad ro barmigardoone
#too sotoone avval bozorgtarin 8 hast va andise2 hast va too sotoone dovom  bozorgtarin 15 hast va andise2 hast va … va khoroojie man yek vector ya bordar hast

#nokte: mibinim dar sotoone sevom 2 ta 7 darim pas avvalin bozorgtarin 7 ro bar migardoone yani oon ke andisesh 0 hast va age argmin bezaram avalin koochaktarin ro baram barmigardoone

array([2, 2, 2, 1])

In [26]:
np.argmax(arr, axis=1)
#hala age axis=1 begzaram miad va dar har row adad haro moghayese mikone va bozorgtarin ro barmigardoone

array([3, 3, 2, 3])

In [ ]:
##pas vaghti axis=1 bashe andise sotoon ha mishe va vaghti axis=0 bashe andise satrha mishe

In [80]:
#dar arrayeye zir jahaye khali ke gozashtam maghadiri hast ke man natoonestam andazeh giri konam
#arr = np.array([,1, 2, 3, ,4])
#dar jahaye khali khode numpy yek np.nan dare ke mitoonam azash estefadeh konam va too jahaye khali begzaram va hala mitoonam ba argmax va argmin andise adade maximum va andise adade minimum ro hesab
#konam
arr = np.array([np.nan,1, 2, 3,np.nan,4])
np.argmax(arr) #mibinam ke argmax ro 0 bargardonnde ke khata hast va bayad andise 4 ro ke 5 hast bargardoone



np.int64(0)

In [81]:
#pas miam az nanargmax estefadeh mikonam ke nanargmax miadva null haro ignore mikone va beyne adad hesab ketab mikone
np.nanargmax(arr)

np.int64(5)

In [32]:
##Kheyli mavaghe yek arraye mesle zir ro ke jahaye khali dare
#arr = np.array([[,1,1.2,4,],[1,,3,,2]])


# ba adad hayi mesle -1 por mikonam ke in -1 ha missingvalue hastan
arr = np.array([[-1,1,1.2,4,-1],[1,-1,3,-1,2]])
#hala age man biam va argmin ro hesab konam behem 0 barmigardoone va dorost ham mige vali khob in be darde man nemikhore chon man goftam ke -1 yani missing value va amalan -1 adade gheyre mojaz hast
#pas adad hayi ke import mikonid va roosh kar mikonid age bekhahid az method hayi mesle argmin ya argmax estefadeh konid bayad deghat konid ke in moshkelat ro nadashte bashan
np.argmin(arr)

np.int64(0)

In [33]:
#hala baraye hale moshkele bala migam boro oonjahayi ke -1 hast ro peyda kon va in ro barabar ba np.nan gharar bede
arr = np.array([[-1,1,1.2,4,-1],[1,-1,3,-1,2]])
arr[arr==-1]=np.nan
arr

array([[nan, 1. , 1.2, 4. , nan],
       [1. , nan, 3. , nan, 2. ]])

In [35]:
np.nanargmin(arr)#ke avvalin koochaktarin adad andisesh 1 hast

np.int64(1)

In [42]:
#dobare yek data dg taarif mikonam
arr = np.array([[10,1,1.2,4,11],[1,10,3,1,2]])
print(arr)
np.argmin(arr, axis=0) #miad va tooye har sotoone matris andise koochaktarin adad ro barmigardoone yani andise sotoone adade koochaktar ro barmigardoone

[[10.   1.   1.2  4.  11. ]
 [ 1.  10.   3.   1.   2. ]]


array([1, 0, 0, 1, 1])

In [82]:
#hala age axis=1 gharar bedam miad va tooye har satre matris andise koochaktarin adad ro barmigardoone yani andise satre adade koochaktar ro barmigardoone ke satre dovom 2 ta 1 darim va nadise
#avvalin 1 ro barmigardoone
arr = np.array([[10,1,1.2,4,11],[1,10,3,1,2]])
print(arr)
np.argmin(arr, axis=1)

[[10.   1.   1.2  4.  11. ]
 [ 1.  10.   3.   1.   2. ]]


array([1, 0])

# numpy.where
numpy.where(condition, [ , x, y, ]/)

In [47]:
##where mige boro begard donbale oon adadi ke tooye oon condition rooberoosh sedgh kone va rooye oon adad ke peyda mikoni bargharar bashe
##nokte inke ma mitoonim ham condition ro khali estefadeh konim va ham ba x va y va age condition ro khali estefadeh konim andis barmigardoone va age condition bargharar bood az arrayeye x entekhab
#kon va age condition bargharar nabood az arraeye y entekhab kon va bargardoon pas age condition True shod boro soraghe vector x va age False shod boro soraghe vector y
#va age ham khali bood andise moadele oon adadi ro bargardoon ke shart roosh bargharar boode

#dar mesale zir age arr>12 bashe miad va andis haye oon anaser ro barmigardoone
arr = np.array([10, 11, 12, 13, 14, 15])
np.where(arr>12)

(array([3, 4, 5]),)

In [46]:
###hala mitoonam begam age in shart bargharar shode boro soraghe yek vector va age bargharar nashod boro soraghe yek vectore dg ,
#dar mesale zir farz mikonim ina adade feshare khoon hastan va age bozorgtar az 13 bood benevis high va dar gheyre in soorat ebenevis low
#pas bayad 2 ta vector baraye high va low taarif konam ke age sedgh kard ya nakard az har kodoom bardare ke tedade vector ha bayad ba tedade moghayese ha yeki bashe
arr = np.array([10, 11, 12, 13, 16, 18])
high = ["H", "H", "H", "H", "H", "H"]
low =  ["L", "L", "L", "L", "L", "L"]
np.where(arr>13, high, low) #inja ham behesh migam ke age shart True bood yani bozorgtar az 13 shod az high bardare va age bozorgtar az 13 nashod az low bardare

array(['L', 'L', 'L', 'L', 'H', 'H'], dtype='<U1')

In [49]:
##hala haminja mitoonam tooye shart ebarate manteghi mesle AND va OR dashte basham va migam masalan age 24 bood be jaye high benevis outband chon dg 24 baraye feshare khoon gheyre manteghie
arr = np.array([10, 11, 12, 13, 16, 24])
high = ["H", "H", "H", "H", "H", "Out-band"]
low =  ["L", "L", "L", "L", "L", "L"]
np.where((arr>13)& (arr>=24), high, low)

array(['L', 'L', 'L', 'L', 'L', 'Out-band'], dtype='<U8')

In [52]:
##hamin ro yek arrayeye 2 bodi ham mitoonim benevisim ke age sharte cond bargharar beshe miad soraghe in matris va age bargharar nashe mire soraghe oon yeki matris
#np.where(con, [[],[]], [[],[]])
#mesalesh mesle zir mishe ke farz mikonim too ghesmate condition yeki rafte va natayeje amadeye True/Flase ovorde
np.where([[True, False],[True, True]], [[1,2],[3,4]], [[5,6],[7,8]])
##chon onsore avvale condition matrix True hast , 1 ro barmidare va onsore badi False hast pas 6 ro bar midare va 2 ta onsore baadi ham True hast pas 3 va 4 ro bar midare
#pas farghesh ba 1 bodi ine ke be jaye vector ya bordar inja matris daram che baraye dorost boodane shart va che nadorost boodane shart

array([[1, 6],
       [3, 4]])

# numpy.argwhere
numpy.argwhere(a)

In [53]:
###be argwhere mitoonam matris ya vector (bordar )bedam va mire andise adad haye gheyre 0 ro behem bar migardoone
data = [[10, 0, 13],[0, 17, 19]]
np.argwhere(data)
##be ma intori barmigardoone va mige too in matris man too satre 0 oonhayi ke gheyre 0 hastan yeki (0,0) hast va digari (0,2) hast  va too satre 1 ham (1,1) va (1,2) gheyre 0 hastan
##dar estelah migim be ezaye har satr dare group by mikone


array([[0, 0],
       [0, 2],
       [1, 1],
       [1, 2]])

In [60]:
#baraye argwhere mitoonam shart ham begzaram
#aval yek data mesle zir dorost mikonam
arr = np.arange(8).reshape(2,4)
arr


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
np.argwhere(arr>4) #inja behesh goftam ke argwhere ro faghatb baraye adad haye bozorgtar az barresi kon ke yani faghat 5,6,7 ro bargardoon ke mishe (1,1) va (1,2) va(1,3)

array([[1, 1],
       [1, 2],
       [1, 3]])

# numpy.nonzero
numpy.nonzero(a)

In [63]:
#in ham mesle argwhere donbale nonzero ha hast vali dg groupby nadare
np.nonzero(data)

(array([0, 0, 1, 1]), array([0, 2, 1, 2]))

In [66]:
#hala mitoonam baraye in ham shart bezaram
np.nonzero(arr>2)

(array([0, 1, 1, 1, 1]), array([3, 0, 1, 2, 3]))

In [67]:
###yek mesale dg . ma ta hala nonzero sohbat kardim
#age man bekham tooye arrayeye zir bebinam 0 ha kojast chikar konam ?
my_arr = np.array([1, 0, 2, 3, 4, 5, 6, 7, 0, 0])
###ma kodoom method ro goftim ke andise elemani ro barmigardoone ke condition toosh sedgh kone ??where
np.where(my_arr==0)

(array([1, 8, 9]),)

# numpy.extract
numpy.extract(condition, arr)

In [69]:
#extract condition va array ro migire va khode oon adad haro bar migardoone yani age oon condition roosh sedgh kard khode adad ro bar migardoone
#aval yek data mesle zir dorost mikonam
arr = np.arange(10).reshape(2,5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
#hala kole adade in arraye ro  -4 kam mikonam
arr -4

array([[-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5]])

In [73]:
#va hala migam age inkaro kardam va >= az 0 bood bargardoon pas condition e man intori mishe
arr -4 >= 0


array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [77]:
#hala in shart ro be extract midam
print(arr -4)
np.extract(arr -4 >= 0,arr)

[[-4 -3 -2 -1  0]
 [ 1  2  3  4  5]]


array([4, 5, 6, 7, 8, 9])

In [78]:
##ya mitoonam yek condition e dg begzaram va begam ke kole adade arraye ro bar 4 taghsiim kon va faghat  oonayi ke baghimandashoon mokhalefe 0 hast ro neshoon bede
print(arr)
np.extract(np.mod(arr, 4)!=0,arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([1, 2, 3, 5, 6, 7, 9])