# Array Operations

In [2]:
import numpy as np
###farz konid ke 2 ta vectore sadeh darim be esm haye "v" va "w"
v = np.array([1, 2, 3])
w = np.array([1, 0 , -1])

#hala mikham amaliate mokhtalef ro rooye in vector ha anjam bedam masalan amaliate jam  , tafrigh  , zarb va ...
print(v + w)
print(v - w)
print(v * w)
print(v / w)
print(v  ** 2)

[2 2 2]
[0 2 4]
[ 1  0 -3]
[ 1. inf -3.]
[1 4 9]


<ipython-input-2-bbe72aacf788>:10: RuntimeWarning: divide by zero encountered in divide
  print(v / w)


In [5]:
##hata mitoonim be jaye vector az matrise 2*2 estefadeh konam va hamoon karaye bala ro barash anjam midam

a = np.array([[3, 1],[2, -1]])
b = np.array([[2, -2],[5, 1]])

print(a + b)
print(a - b)
print(a * b) ##Inja zarbe matrisi nemikone balke eleman ba eleman ba ham zarb mikone anasere matris ro
print(a / b)
print(a  ** 2)


[[ 5 -1]
 [ 7  0]]
[[ 1  3]
 [-3 -2]]
[[ 6 -2]
 [10 -1]]
[[ 1.5 -0.5]
 [ 0.4 -1. ]]
[[9 1]
 [4 1]]


In [22]:
#ma dar numpy chand noe zarb darim ke mikham anvae inaro baham bebinim
#dar ghadame avval miam va 2 ta arraye taarif mikonam

A = np.array([[1, 2],[3, 4]]) #Define an array
B = np.array([[1, 1],[2, 2]])
C = np.multiply(A, B)
print("C_Array(Multiply):", C)
print("-----------------------")

#inja 2 ta matris taarif mikonam

#`np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead. too dore gofte shodeh bood : A_mat = np.mat(A)
A_mat = np.asmatrix(A) #Define a matrix
B_mat = np.asmatrix(B)
C_mat = np.multiply(A_mat, B_mat)
print("C_mat(Multiply):", C_mat)
print("-----------------------")

#inja 2 ta vector taarif mikonam

A_v = np.array([1, 2, 3, 4])
B_v = np.array([1, 1, 2, 2])

C_v = np.multiply(A_v, B_v)
print("C_Vector(Multiply):", C_v)
print("-----------------------")


###mibinim ke function e multiply , zarb ro be soorate 'element wise' ya 'hadamard' anjam mide va zarbe matrisi nist va dar har 3 halat ham, element wise bood yani che voroodi arraye bashe , che vector
#va che matris

C_Array(Multiply): [[1 2]
 [6 8]]
-----------------------
C_mat(Multiply): [[1 2]
 [6 8]]
-----------------------
C_Vector(Multiply): [1 2 6 8]
-----------------------


In [23]:
###functione e badi baraye zarb kardan 'dot' hast

A = np.array([[1, 2],[3, 4]])
B = np.array([[1, 1],[2, 2]])
C_dot = np.dot(A, B)
print("C_Array(dot):", C_dot)
print("-----------------------")

A_mat = np.asmatrix(A)
B_mat = np.asmatrix(B)
C_mat_dot = np.dot(A_mat, B_mat)
print("C_mat(dot):", C_mat_dot)
print("-----------------------")


A_v = np.array([1, 2, 3, 4])
B_v = np.array([1, 1, 2, 2])

C_v_dot = np.dot(A_v, B_v)
print("C_Vector(dot):", C_v_dot)
print("-----------------------")

###mibinim ke function e dot ,zarb ro be soorate 'matrix multiplication' ya 'zarbe matrisi' anjam mide va zarbe matrisi ro faghat zamani ke  voroodi arraye  va  matris bashe anjam mide vali age voroodi
#vector bashe doone doone dar ham zarb kard va baham jam kard ke natije shod 17 ke vaghti sum rooye zarbe 2 ta vector emal mishe behesh migim "sum of hadamard"


C_Array(dot): [[ 5  5]
 [11 11]]
-----------------------
C_mat(dot): [[ 5  5]
 [11 11]]
-----------------------
C_Vector(dot): 17
-----------------------


In [31]:
#####functione e badi baraye zarb kardan 'star' ya '*' hast
A = np.array([[1, 2],[3, 4]])
B = np.array([[1, 1],[2, 2]])
C_star = A*B
print("C_Array(star):", C_star)
print("-----------------------")

A_mat = np.asmatrix(A)
B_mat = np.asmatrix(B)
C_mat_star = A_mat*B_mat
print("C_mat(star):", C_mat_star)
print("-----------------------")


A_v = np.array([1, 2, 3, 4])
B_v = np.array([1, 1, 2, 2])

C_v_star = A_v*B_v
print("C_Vector(star):", C_v_star)
print("-----------------------")

###mibinim ke function e star age voroodi matris bashe ,zarb ro be soorate 'matrix multiplication' ya 'zarbe matrisi' anjam mide
#va age voroodi array bashe , zarb ro be soorate 'element wise' ya 'hadamard' anjam mide
#va age voroodi vector bashe , , zarb ro be soorate 'element wise' ya 'hadamard' anjam mide

C_Array(star): [[1 2]
 [6 8]]
-----------------------
C_mat(star): [[ 5  5]
 [11 11]]
-----------------------
C_Vector(star): [1 2 6 8]
-----------------------


In [30]:
#####functione e badi baraye zarb kardan 'at' ya '@' hast

A = np.array([[1, 2],[3, 4]])
B = np.array([[1, 1],[2, 2]])
C_at = A@B
print("C_Array(@):", C_at)
print("-----------------------")

A_mat = np.asmatrix(A)
B_mat = np.asmatrix(B)
C_mat_at = A_mat@B_mat
print("C_mat(@):", C_mat_at)
print("-----------------------")


A_v = np.array([1, 2, 3, 4])
B_v = np.array([1, 1, 2, 2])

C_v_at = A_v@B_v
print("C_Vector(@):", C_v_at)
print("-----------------------")

###mibinim ke function e @ age voroodi arraye ya matris bashe ,zarb ro be soorate 'matrix multiplication' ya 'zarbe matrisi' anjam mide
#va age voroodi vector bashe , natije shod 17 ke vaghti sum rooye zarbe 2 ta vector emal mishe behesh migim "sum of hadamard"

C_Array(@): [[ 5  5]
 [11 11]]
-----------------------
C_mat(@): [[ 5  5]
 [11 11]]
-----------------------
C_Vector(@): 17
-----------------------


In [33]:
###conclusion

#1-age az function e multiply estefadeh konam , voroodie man age  vector , array ya matris bashe khorooji ro be raveshe 'hadamart' ya 'element-wise' hesab mikone

#2-age az function e dot estefadeh konam , voroodie man age  array ya matris bashe, khorooji ro be raveshe 'matrix multiplication' ya 'zarbe matrisi' hesab mikone va age voroodi vector bashe khorooji
#ro be raveshe "sum of hadamard" hesab mikone

#3-age az function e star estefadeh konam ,  voroodie man age  array ya vector bashe, khorooji ro be raveshe 'hadamart' ya 'element-wise' hesab mikone va va age voroodi matris bashe khorooji
#ro be raveshe 'matrix multiplication' hesab mikone

#4-age az function e at estefadeh konam , voroodie man age  array ya matris bashe, khorooji ro be raveshe 'matrix multiplication' ya 'zarbe matrisi' hesab mikone va age voroodi vector bashe khorooji
#ro be raveshe "sum of hadamard" hesab mikone


#pas @ va 'dot' kamelan shabihe ham kar mikonan
#in yek dastebandie koli az anvae zarb dar numpy hast