In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3]) #inja as input behesh list dadam va behem array bargardoond
arr #in dar classes array hast

array([1, 2, 3])

In [3]:
mat = np.matrix([1, 2, 3])  #inja ham as input behesh list dadam va behem matrix bargardoond
mat #in dar classe matrix hast ke zir classi az array hast

matrix([[1, 2, 3]])

In [7]:
arr1 = np.array(arr) ##indafe be  jaye inke too voroodi list bedam miam va too voroodi yek numpy array midam ke khorooji ham numpy array mishe
arr1

array([1, 2, 3])

In [8]:
arr1 is arr ###inja mikham bebinam aya in 2 ta object yeki hastan ??? na yek object yeksan nistan ba tavajoh be inke khorooji hash az nazare meghdari va adadi yeksan hast va har 2 shode :
## array([1, 2, 3])

False

In [ ]:
#####chera in 2 ta  yani arr va arr1 2 ta object motefavet hastan ??? chon default copy True  hast yani inke miad yek copy dar ekhtiare ma gharar mide va in baes mishe ke khoroojie np.array
##ba voroodie oon yeksan nabashe

In [10]:
###pas age taghyiri too 'arr' bedam roo 'arr1' emal nemishe chon tghyirat ro rooye copy emal mikone va original data man dast nakhorde
arr1[0] = 10
arr1


array([10,  2,  3])

In [11]:
arr

array([1, 2, 3])

In [12]:
#### hala age copy ro False konam chi ???? in dafe mige True chon copy nakardim va az nazare object e yeksan hastan
np.array(arr, copy = False) is arr

True

In [14]:
####hala age id inha ro ham negah konim mibinim ke id shoon ham yeksan hast pas 2 ta same object hastan chon andis tooye memory shoon yeksan hast
id(arr)

132826104970768

In [28]:
id(np.array(arr, copy = False))

132826104970768

In [17]:
np.may_share_memory(np.array(arr, copy = False), arr) ###in function numpy barrsi mikone ke aya in 2 object az yek fazaye eshterakie memory estefadeh mikonan

True

In [18]:
###va age too in halat andise 0 ro taghyir bedam too 'arr' ham taghyir mikone chera ? chon az nazare object e yeksan hastan
np.array(arr, copy = False)[0] = 10
arr

array([10,  2,  3])

In [19]:
##hala age  ba hamoon copie false biam va dtype ro be float64 taghyir bedam baz ham dg baham yek object nistan chon dtype esh  ba dtype voroodi yeksan nist va numpy yek copy azash ro behem mide
np.array(arr, dtype = np.float64, copy = False) is arr

False

In [20]:
###va mibinim ke id hashoon ham motefavet hast
id(np.array(arr, dtype = np.float64, copy = False))

132825130791824

In [21]:
id(arr)

132826104970768

In [22]:
#np.may_share_memory ham mige False hast va yeki nistan yani az yek fazaye eshterakie memory estefadeh nemikonan
##momkene yek moghe 2 ta object dashte bashim ke 'np.array(arr, dtype = np.float64, copy = False) is arr' barashoon False bashe vali 'np.may_share_memory' barashoon True bashe oon moghe migim ke
##2 ta object hastan ke az yek fazaye memory estefadeh mikonan
np.may_share_memory(np.array(arr, dtype = np.float64, copy = False), arr)

False

In [23]:
##hala in mavared ro baraye matrix ham check konim ke mibinim False hast chon copy dar halate default True hast
np.array(mat) is mat

False

In [24]:
##id haro ham check mikonim
id(np.array(mat))

132825118427824

In [25]:
id(mat)

132826114989392

In [37]:
np.may_share_memory(np.array(mat), mat) ##mibinim ke 'np.may_share_memory' ham False hast

False

In [27]:
###pas age rooye 'np.array(mat)' ham taghyiri bedam rooye 'mat' emal nemishe
#nokte injast ke chon in az classe matrix hast age man yek dimension ro taghyir bedam masalan mesel zir 0 esh konam , in kolesh ro taghyir mide yani kole satr 0 mishe chon in '[1, 2, 3]' kolan
#satre 0 hast
np.array(mat)[0] = 10
mat

matrix([[1, 2, 3]])

In [30]:
##mesle bala miam va copy ro False mikonam va entezar daram ke indafe khoroojie np.array ham az type matrix bashe vali :
np.array(mat, copy = False) is mat

False

In [38]:
np.array(mat, copy = False) ##elatesh ine ke khoroojie 'np.array(mat, copy = False)' az classe array hast va 'mat' az classe matrix hast

array([[10, 10, 10]])

In [35]:
## va id hashoon ham motefavet hast ke neshoon mide ba inke copy ham False hast inha 2 ta object motefavet hastand
id(np.array(mat, copy = False))

132825118440208

In [36]:
id(mat)

132826114989392

In [33]:
###vali nokteye jalebesh ine ke man age taghyiri rooye 'np.array(mat, copy = False)' bedam in taghyir rooye 'mat' ham emal mishe. chera ?????????
np.array(mat, copy = False)[0] = 10
mat

matrix([[10, 10, 10]])

In [39]:
###in nshoon mide ke in 2 ta object daran az yek memory space estefadeh mikonan ke ba tavajoh be id ha ke motefavet hastan neshoon mide ke in 2 object motefavet hastan vali be yek
## jaye moshtarak az hafeze eshare mikone va baraye hamin ham hast ke vaghti roo yeki taghyir midam , rooye digari ham emal mishe chon fazaye eshterakie memory yeksan hast
##elate motefavet boodane 2 ta object ine ke voroodie man az classe 'matrix' hast ke zir classi az array hast pas 2 ta object motefavet hastan
np.may_share_memory(np.array(mat, copy = False), mat)

True

In [40]:
##yademoon hast ke ba option 'subok' miad az class object e voroodi ke behesh midi peyravi mikone ke dar halate default False hast ke inja oon ro True mikonam
##ke in kari ke mikone ine ke mige to vaghti voroodit classe matrix hast va zir classi az array hast , khoroojit ro ba hasbe oon object e ke behet midam dar nazar begir yani az classe in voroodi
#baraye khodet yek zirclass ya subclass besaz va mibinam ke khoroojie man az classe matrix hast va dg az classe array nist

np.array(mat, copy = False, subok = True)

matrix([[10, 10, 10]])

In [45]:
##ke indafe mibinim in True mide
np.array(mat, copy = False, subok = True) is mat


True

In [43]:
##va id hashoon ham yeksane
id(np.array(mat, copy = False, subok = True))

132826114989392

In [44]:
id(mat)

132826114989392

In [46]:
np.may_share_memory(np.array(mat, copy = False, subok = True), mat)

True

In [ ]:
##jambandi : pas vaghti subok ro begzaram True , khorooji ke behesh midam az noe hamoon voroodi hast ke daram behesh midam va az noe array nist
##va inham kheyli mohem hast chon age khorooji man matrix bashe va bezanam 'np.array(mat, copy = False)[0] = 10' miad yek satre kamel ro taghyir mide va age khoroojie man array bashe
## va bezanam 'np.array(arr, copy = False)[0] = 10' faghat onsore ya derayey 0 ro taghyir mide

In [48]:
##nokte: har ja type ro taghyir bedam behem yek copy barmigardoone va 2 ta object motefavet mishan
np.array(mat, copy = False, subok = True, dtype = np.float64) is mat

False

# Asarray method
in 2 ta ke payin neveshtim moadele ham hastan

In [50]:
np.array(mat, copy = False) is mat

False

In [49]:
np.asarray(mat) is mat

False

# Asanyarray method

in 2 ta ke payin neveshtim moadele ham hastan





In [4]:
np.array(mat, copy = False, subok = True) is mat

True

In [5]:
np.asanyarray(mat) is mat

True