In [7]:
import numpy as np
x = np.arange(6) ##function e arange miad adade motevali baraye ma  tolid mikone
x

array([0, 1, 2, 3, 4, 5])

In [8]:
x.shape #shape mige  ke x yek arraye 1 bodi hast ke 1 * 6 hast

(6,)

In [10]:
x = np.arange(6).reshape(2,3)##ba methode reshape miam va shape ro taghyir midam
x

array([[0, 1, 2],
       [3, 4, 5]])

# Ascontiguousarray

In [13]:
y = np.ascontiguousarray(x) ##in method miad va data hamo yekja too hafeze zakhire mikone va dar halate default C style ham hast yani too hafeze data haro C style zakhire mikone
y

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
y.flags ###flags miad va property haye tooye y ro baram list mikone va mibinim ke C_CONTIGUOUS hast

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [15]:
z = y.T #in be ma taranahadeye matrise y ro mide va mibinim ke F_CONTIGUOUS hast
z

array([[0, 3],
       [1, 4],
       [2, 5]])

# Asmatrix
in methode asmatrix ba function e matrix ke taarif karde boodim cher farghi dare ???

In [22]:
am = np.array([[4, 6],[9, 10]])
mat = np.asmatrix(am)

am

array([[ 4,  6],
       [ 9, 10]])

In [24]:
mat ##mibinim khorooji az classe matrix hast

matrix([[ 4,  6],
        [ 9, 10]])

In [25]:
am[0][1] = 1 #inja migam ke satre 0 va elemane 1 ro begzar 1 yani be jaye 6 begzar 1 va mibinim ke in taghyir ro dadeh
am

array([[ 4,  1],
       [ 9, 10]])

In [31]:
mat ##mibinim ke taghyirat ro rooye 'mat' ham emal karde pas methode 'asmatrix' mesle function e 'matrix' mimoone ba in tafavot ke copy dar halate default esh False hast
## asmatrix == matrix(data, copy = False)

matrix([[ 4,  1],
        [ 9, 10]])

In [30]:
##age bekham khode arraye matris ro mostaghim bebinam be soorate zir ke mibinim 6 ba 1 jaygozin shode
np.asmatrix(am)[0, 1]

1

# Copy

In [32]:
c = np.array([3, 4, 5])
z = np.copy(c) ##entezar daram ke vaghti taghyiri rooye 'c' midam dg rooye 'z' nabinam chon 'z' yek copy az 'c' hast
z

array([3, 4, 5])

In [33]:
c[0] = 9
print(c, z)

[9 4 5] [3 4 5]


In [35]:
###hala age yek 'y' ham taarif konam va oon ro be 'c' entesab bedam be soorate zir mibinim ke 'y' ham taghyir karde
y = c
c[0] = 9
print(c, z , y)


[9 4 5] [3 4 5] [9 4 5]


In [ ]:
##pas be in natije miresam ke vaghti 'y' ro barabar ba 'c' gharar midam yek reference ya yek esharegar dare tahye mikone

In [42]:
###hala hamin methode copy ro dar yek arraye yekam complex tar estefadeh mikonam
a = np.array([1, 'hesam', [1, 2, 3]])
b = np.copy(a)
b[2][0] = 110 ##hala miam 2 elemente dovvom va onsore 0 ro taghyir midam
print(a, b)
####error of this code
#from numpy import array
#test_list = [[1,2],3]
#x = array(test_list) #ValueError: setting an array element with a sequence.
#????
#1-It's failing because the array is non-rectangular. If we change the 3 to [3, 4] then it works.
#array([[1, 2], [3, 4]])
#2-also, the data in an array must be homogeneous. if your element types are list and int, that's not homogeneous. if you changed the dtype to py_object it would work because they'd be of the homogeneous
####type object. that's the fundamental distinction -- lists are inhomogeneous, arrays are homogeneous. if you want to store inhomogeneous data types, use a list

#x = array([[1,2],3], dtype=object)
https://stackoverflow.com/questions/4523432/why-cant-i-create-a-numpy-array-like-this-array1-2-3


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [44]:
a = np.array([1, 'hesam', [1, 2, 3]], dtype=object)
b = np.copy(a)
b[2][0] = 110 ##hala miam 2 elemente dovvom va onsore 0 ro taghyir midam
print(a, b)

[1 'hesam' list([110, 2, 3])] [1 'hesam' list([110, 2, 3])]


In [45]:
###chera dar bala taghyirat rooye 'a' ham emal shode ???
#ma yek 'shallow copy' darim va yek 'deep copy' va vaghti ke man shallow copy estefadeh konam rooye nested list emal nemishe
#pas oon methode copy ke dar numpy vojood dare az noe shallow copy hast chon 110 too 'a' va 'b' taghyir karde
#pas bayad biam az deep copy estefadeh konam
import copy
a1 = np.array([1, 'hesam', [1, 2, 3]], dtype=object)
b1 = copy.deepcopy(a)
b[2][0] = 110 ##hala miam 2 elemente dovvom va onsore 0 ro taghyir midam
print(a1, b1)  ##va hala mibinim ke dorost shod va original data ro dast nazad

[1 'hesam' list([1, 2, 3])] [1 'hesam' list([110, 2, 3])]


# *Frombuffer*

In [49]:
st = b'hesam'
np.frombuffer(st, dtype='S1', count = -1)
##count moshakhas mikone ke chand ta az oon buffer ro bekhoonam va age count barabare -1 bashe yani hameye oon ro bekhoon
##dar zir mibinim ke chizi ke bargardoone ine ke oomade kole string ke binary format hast ro khoonde va 1-dimensional too yek arraye gharar dadeh

array([b'h', b'e', b's', b'a', b'm'], dtype='|S1')

In [50]:
##yek option offset ham daram ke mige az koja shoroo kon be khoondan masalan age begam offset 1 va count 2 mire az 'e' tooye hesam shoroo mikone va 2 ta mikhoone
np.frombuffer(st, dtype='S1', count = 2, offset = 1)

array([b'e', b's'], dtype='|S1')

In [51]:
##offset dar halate default 0 hast yani age moshakhas nashe az avval shoroo mikone be khoondan
np.frombuffer(st, dtype='S1', count = 2)

array([b'h', b'e'], dtype='|S1')

In [52]:
np.frombuffer(st, dtype='S1', count = 1, offset = 3) ##in mige az offset e 3 shoroo kon va 1 character bekhoon

array([b'a'], dtype='|S1')