# Fromfunction

In [6]:
#masalan dar shekle zir mikham har ja coordinate ha baham barabar hastan (yani harja i=j) biad va bejash True or False begzare
import numpy as np
np.fromfunction (lambda i,j : i == j , (3, 3), dtype = int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
##ya masalan mitoonam yek function benevisam ke i ro dar j zarb kone
np.fromfunction (lambda i,j : i * j , (3, 3), dtype = int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
##ya masalan mitoonam yek function benevisam ke i ro ba j jam kone
np.fromfunction (lambda i,j : i + j , (3, 3), dtype = int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Fromiter

In [ ]:
itr = (x*x for x in range(5))  #man yek tuple misazam ke migam khoroojie tuple x*x hast baraye x haye beyne  0 ta 4
np.fromiter(itr, dtype = float) ##hala yek arraye misazam va voroodi ke behesh midam iterable hast (itr) va baraye man az in iterable yek arrayeye numpy sakht

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
##balayi ro intori ham mishe nevesht va mishe 'dtype' ro hazf kard
np.fromiter(itr, float)

array([], dtype=float64)

In [ ]:
##mitoonam be jaye float biam int ro behesh bedam
itr = (x*x for x in range(5))
np.fromiter(itr, int)

array([ 0,  1,  4,  9, 16])

In [ ]:
##Mitoonam behesh count ham bedam ke chand ta az oon ro bekhoon
itr = (x*x for x in range(5))
np.fromiter(itr, int, count = 2)

array([0, 1])

# Fromstring

In [ ]:
np.fromstring('1 2 3 4 5', dtype = int, sep = ' ')

array([1, 2, 3, 4, 5])

In [ ]:
np.fromstring('1,2,3,4,5', dtype = int, sep = ',')

array([1, 2, 3, 4, 5])

# loadtxt

In [29]:
#baraye in bakhsh yek file text be onvane dataset darim ke name esh 'eg6-a-student-data.txt' hast va in ro bayad ebteda load konam
file_name = '/content/sample_data/eg6-a-student-data.txt'
#miam va barash dtype taarif mikonam ke sotoone 'sex' va 'height' ma che type dashte bashe
#va hata mitoonam esmesh ham avaz konam ke ma inja be jaye 'sex' esmesh ro migzarim 'gender'
#pas dar zir baraye chand ta sotoon , dtype taarif kardam
dtype1 = np.dtype([('gender', 'S1'),('height', 'f8')]) ###Most important
#hala mikham file ro load konam pas az np.loadtxt estefadeh karde va dtype ro hamooni ke taarif kardam gharar midam va ba skiprows ham az 9 satre avvale
#dataset miparam chon 9 satre avval data morede niaze man nist va hamchenin man mikham rooye sotoon haye 'sex' va 'weight' kar konam pas ba usecols oonha ro
#moshakhas mikonam
arr = np.loadtxt(file_name, dtype = dtype1, skiprows = 9, usecols=(1, 3))
arr #alan arraye man ro 2 ta sotoonesh ro ovord vali sotoone sex ke be formate binary ovorde va sotoone height
#mibinim ke khate 14 ke comment shodeh too data nist

array([(b'M', 1.82), (b'M', 1.77), (b'F', 1.68), (b'M', 1.72),
       (b'F', 1.78), (b'F', 1.6 ), (b'M', 1.72), (b'M', 1.83),
       (b'F', 1.56), (b'F', 1.64), (b'M', 1.63), (b'M', 1.67),
       (b'M', 1.66), (b'F', 1.59), (b'F', 1.7 ), (b'M', 1.97),
       (b'F', 1.66), (b'F', 1.63), (b'M', 1.69)],
      dtype=[('gender', 'S1'), ('height', '<f8')])

In [30]:
arr['gender'] #ba in dastoor faghat yek array 1 bodi behem mide ke faghat gender ha toosh hastan

array([b'M', b'M', b'F', b'M', b'F', b'F', b'M', b'M', b'F', b'F', b'M',
       b'M', b'M', b'F', b'F', b'M', b'F', b'F', b'M'], dtype='|S1')

In [31]:
#hala man in ro barabar ba b'M' gharar midam va in baes mishe harja male bood ro baram True kone va harja male nabood ro False kone
m = arr['gender'] == b'M' #while arr[gender]  is equal to M ,the output will be True else False
m

array([ True,  True, False,  True, False, False,  True,  True, False,
       False,  True,  True,  True, False, False,  True, False, False,
        True])

In [32]:
#hala age bekham faghat ghade mardharo behem bede
arr['height'][m]#in mige height ro behem bede vali zamani ke 'M' bashe ke 'M' haye True ro too arraye 'm' rikhtam

array([1.82, 1.77, 1.72, 1.72, 1.83, 1.63, 1.67, 1.66, 1.97, 1.69])

In [33]:
#hala mikham miangine ghade mard haro be dast biaram
male_avg_height = arr['height'][m].mean()
male_avg_height

1.748

In [34]:
##chetor ba ye taghyire koochak miangine ghade khanom haro ham be dast biaram ????
#man male haro rikhtam too arraye 'm' pas baraye 'female' ha bayad NOT 'm' ro be dast biaram
fmale_avg_height = arr['height'][~m].mean()
fmale_avg_height

1.6488888888888888

In [35]:
print('Male Average: {:.2f}m and Female Average: {:.2f}m'.format(male_avg_height, fmale_avg_height))

Male Average: 1.75m and Female Average: 1.65m


In [46]:
###age dar dataset bekham rooye sotoone 'weight' kar konam yek seri khate tire dare ke be inha migan missing value
#ke bayad in khate tireh haro yek kari bokonam bahashoon masalan mitoonam in - haro ba yek adadi ke motemayez bashe jaygozin konam
#masalan miam hamshoon ro ba adade -100 tavasote function e zir jaygozin mikonam

def correct_weight(s):
  try:
    return float(s)
  except ValueError:##man bala goftam ke 'return float' vali khate tire ya - ke nemitoone be shekle float dar biad pas exception mikhore va in except baraye in hast
    return -100.  ###in dot dar entehaye -100 baraye in hast ke float bashe



In [50]:
###hala yek dtype2 mesle bala taarif mikonam faghat indafe az weight estefadeh mikonam
dtype2 = np.dtype([('gender', 'S1'),('weight', 'f8')])  ###Most important

##hala bayad data ro load konim va chon mikham rooye sotoone weight yek correction bezanam , yek converter dare ke mitoonam toosh begam :rooye sotoone 4 om
#in function e  'correct_weight' ro emal kon yani boro tak take voroodi hash ro begir va be float tabdil kon va age error khord -100 begzar

arr2 = np.loadtxt(file_name, dtype = dtype2, skiprows = 9, usecols=(1, 4), converters = {4:correct_weight})
arr2

array([(b'M',   92.4), (b'M',   80.9), (b'F',   69.7), (b'M',   75.5),
       (b'F',   82.1), (b'F', -100. ), (b'M',   77.2), (b'M',   88.9),
       (b'F',   56.3), (b'F',   65. ), (b'M',   73. ), (b'M',   89.8),
       (b'M',   75.1), (b'F',   67.3), (b'F', -100. ), (b'M',   89.2),
       (b'F',   63.8), (b'F',   64.4), (b'M', -100. )],
      dtype=[('gender', 'S1'), ('weight', '<f8')])

In [53]:
###hala mikham begam ke 'weight' age mosbat bood baraye man True dar nazar begir va age manfi bood , aslan baraye man lahaz nakon va False begzar
corrected_weight = arr2['weight'] > 0
corrected_weight

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False])

In [60]:
###hala milkham dobare miangine vazn ro baraye aghayan va miangine vazn ro baraye khanoom ha hesab konam
#male_Av_weight = arr2['weight'][] ##in yani mikham miangin ro rooye sotoone 'weight' be dast biaram va hala mikham begam be che sharti ???
#1-be sharti ke male bashand ke mishe matrise 'm'
#2-be sharti ke 'corrected_weight' oon True bashe
#pas mishe in shekil :
male_Av_weight = arr2['weight'][corrected_weight & m]
#hala bayad miangine in ro hesab konim va baraye female ha hamin ro ba NOT 'm' benevisim
male_Av_weight = arr2['weight'][corrected_weight & m].mean() #inja goftam ke age coorected_weight man mosbat bashe va male bashe (yani tooye arraye 'm' bashe miangin begire)
fmale_Av_weight = arr2['weight'][corrected_weight & ~m].mean() #inja goftam ke age coorected_weight man manfi bashe va fmale bashe (yani tooye arraye 'm' nabashe miangin begire)
#hamoon balayi ro minevisam , faghat be jaye meter minevisam  kg
print('Male Average: {:.2f}kg and Female Average: {:.2f}kg'.format(male_Av_weight, fmale_Av_weight))

Male Average: 82.44kg and Female Average: 66.94kg
