In [ ]:
#I/O be in manie ke chetori az yek file bekhoonim va dakhelesh benevisim .chio bekhoonim va benevisim ??hamoon arraye hayi ke ijad kardim va hamoon arraye hayi ke khoroojie mohasebatemoon hast
# dar reference ma input va output 2 ta section dare 1-binary files 2- text files ke binary files be in manie ke saving ma be shekle binary hast va text files ke saving ma be shekle text hast
https://numpy.org/doc/stable/reference/routines.io.html


In [ ]:
#text file ha ghabele khoondane yani be hamoon soorat mitoonam bekhoonam vali binary file haro na va hatman bayad dakhele python load esh konam ta betoonam bekhoonam ya formatesh ro taghyir bedam
#be UTF8 ya formate dg e ke betoonam bekhoonamesh

#formate file haye binary NPY va NPZ hastan

In [3]:
#yek arraye be shekle zir taarif mikonam
import numpy as np
arr = np.array([i+j for i in range(2) for j in range(2)])
print("Array is:", arr)

Array is: [0 1 1 2]


In [2]:
#ke albate age too code bala jaye [] ro avaz konim object esh ro behem neshoon mide ke ba in kari nadarim va ma rooye balayi kar mikonim
arr1 = np.array([i+j] for i in range(2) for j in range(2))
print("Array is:", arr1)

Array is: <generator object <genexpr> at 0x7934cf44adc0>


In [6]:
#hala age bekham ino zakhire konam  ba np.save() inkaro mikonam
#vali chon formattesh binary hast nemitoonam bebinam , bayad loadesh konam ya formattesh ro be UTF8 ya ASCII change konam ke btoonam bebinam
np.save("hesamarray", arr) ##inja esme file ro ke bedam mire tooye current working path zakhire mikone ke mitoonam behesh path ham bedam
print("hesamarray.npy")

hesamarray.npy


In [4]:
print(np.load("hesamarray.npy"))

[0 1 1 2]


In [10]:
##save kardan ba formate npz va load kardan e mojadade oon
np.savez("hesamarrayz", arr) ##using *args amalan too in halat daram az raveshe *args estefadeh mikonam
loaded_array = np.load("hesamarrayz.npz")
print(loaded_array)  ###ke mibinim dare object mano barmigardoone na khode array ro va elatesh ham in hast ke too formate npz content ya mohatavaye arraye dakhele
#yek file ya container zakhire mishe ke esmeshro behehm dadeh dar zir "arr_0" pas mohatavaye arraye rafte tooye file "arr_0" dar objecte in npz


NpzFile 'hesamarrayz.npz' with keys: arr_0


In [12]:
##pas mohtavaye oon file ro intori mibinam
print(loaded_array['arr_0'])

[0 1 1 2]


In [14]:
np.savez("hesamarrayz", x = arr) ##using **kwds amalan too in halat daram az raveshe **kwds estefadeh mikonam ke masalan inja be jaye inke khode arraye ro
#bedam , barash yek name mesle 'x' dar nazar migiram
loaded_array = np.load("hesamarrayz.npz")
print(loaded_array)
print(loaded_array['x']) ###va inja in esm ro be jaye 'arr_0' seda mizanam ke chon dar halate default oon 'arr_0' ro be onvane name e  file haye dakhelie arraye
# dar nazar nemigire va be jash hamoon 'x' ro seda mizanam

#pas vaghti x = arr ro migzaram in yek halate keyword ya **kwds hast ke in x esme arrayeye man dar npz hast ke mitoonam ba eshare be andise x behesh dastresi dashte
#basham

NpzFile 'hesamarrayz.npz' with keys: x
[0 1 1 2]


In [16]:
np.savez_compressed("hesamarrayz", x = arr) ##age az compressed estefadeh konam  arrayeye hesamarrayz be soorate compressed shode rooye disk zakhire mishe
loaded_array = np.load("hesamarrayz.npz")
print(loaded_array)
print(loaded_array['x'])

NpzFile 'hesamarrayz.npz' with keys: x
[0 1 1 2]


In [18]:
##dar session ghabli np.loadtxt ro barresi kardim hala mikham bebinam ke age bekham savetxt estefadeh konam che option hayi daram
#avval yek arraye be esme 'x' misazam ba np.arange ke 20 ta ozv dashte bashe va reshape esh ham mikonam ke 4 ta satr dashte bashe va 5 ta sotoon
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
#hala age ino bekham ba savetxt , save esh konam , avval bayad behesh yek name(fname) bedam ke masalan migzaram 'x_array' va bad behesh esme arraye e ke mikham zakhire
#konam bedam ke inja esmesh 'x' hast va bad bayad behesh format ya fmt bedam ke ba format taarif mishe ke chetori oon ro tooye file neshoon bede
#ke formate default esh '%.18e' hast ke mige bakhshe sahih ke hichi vali bakhshe asharie oon 18 ta raghame ashari begire va chon 'e' hast yani mishe namade elmi
#delimiter ke mige joda konandeh am chi bashe ke dar halate default ' ' ya space hast
#hala age code zir ro ba mavarede bala ke goftim ejra konim file 'x_array' ro baramoon ijad mikone
x = np.arange(20).reshape(4, 5) #1D and 2D tavajoh konid ke savetext baraye arraye haye 1 bodi va 2 bodi estefadeh mishe va baraye arraye haye 3 bodi va bishtar
# ghabele estefadeh nist
np.savetxt('x_array.txt', x, delimiter=' ')

#ke too file ijad shode mibinam ke hameye adad ha ba 18 raghame ashar hast va delimiter space hast

In [22]:
#mitoonam delimiter ro ',' begzaram
np.savetxt('x_array.txt', x, delimiter=',')

In [23]:
#mitoonam format ro '%.2f' begzaram yani bade bakhshe sahih ta 2 raghame ashari bashe va 'f' dar inja yani 'float' bahse
np.savetxt('x_array.txt', x, delimiter=',', fmt='%.2f')

In [24]:
#ya mitoone ta 3 raghame ashari bashe
np.savetxt('x_array.txt', x, delimiter=',', fmt='%.3f')

In [25]:
#ya hata mitoonim be soorate integer neshoon bedim
np.savetxt('x_array.txt', x, delimiter=',', fmt='%d')

In [26]:
# ya hata mitoonam '%3d' begzaram ke baraye har adad 3 ta position lahaz mikone va age maximum adad hamoon 2 raghami bashe '2d' va
#age maximum adad hamoon 3 raghami bashe '3d' migzarim
np.savetxt('x_array.txt', x, delimiter=',', fmt='%3d')
#inja  chon maximum adad hamoon 2 raghami hast az hamoon '2d' estefadeh mikonam


In [28]:
# ke mitoonam behesh begam baraye adade yek raghami space haye khali ro ba 0 por kone
np.savetxt('x_array.txt', x, delimiter=',', fmt='%02d')

In [29]:
#in kar ro baraye ashari ha ham mitoonam bokonam
np.savetxt('x_array.txt', x, delimiter=',', fmt='%2.2f')

In [30]:
#hala baraye inke adad ha zire ham gharar begiran migam ke bozorgtarin adad yani '19.00' chand ta position dare?
#5 ta
#pas minevisam  %5.2f
np.savetxt('x_array.txt', x, delimiter=',', fmt='%5.2f')
#option e 'comments' ro dar 'genfromtxt' migam

In [38]:
#numpy.fromregex
file = open('my_reg.txt', 'w')## yek file be esme 'my_reg' dorost mikonam va mikham format esh 'w' bashe yani dakhelesh
# benevisam
_ = file.write("1234 hesam\n5678 Alireza\n91011 uvwxyz") #ba file.write inha ro tooye file neveshtam va badesh be variable
#ba esme _ assign kardam ke variable ba esme '_' yani mirizam file ro tooye yek variable vali baram mohem nist
# ke esme variable chi bashe
file.close() #file ro mibandam
#age code bala ro ejra konam baram file 'my_reg' ro misazeh

#hala regex am ro taarif mikonam
regexp = r"(\d+)\s+(.....)"##in mige ke avval adad haro joda kon (ba \d) va badesh space dashte bashim (ba \s) va badesh 5 ta character dashte bashim ba (.....)
#nokteye mohem injast ke in paranthes ha baese tashkile groupi az oonha mishe yani alan integer ha mishan yek group va character ha mishan yek group e dg pas man
#alan 2 ta category daram adad va string
out = np.fromregex('my_reg.txt', regexp, dtype=[('num', np.int64), ('key', 'S5')]) ##inja miam va migam voroodim bashe file my_reg.txt va regexp ham ke bala taarif kardam ro be in file emal kon
#va data type ham 2 model bood dg adad va string ke yek tuple taarif mikonam va baraye adad esme 'num' ro taarif mikonam ba type 'int64' va baraye string ham esme 'key'
#ro taarif mikonam ba type 'S5'
out  ###mibinim behemoon formate arraye bargardoond yani out[0] ma mishe ( 1234, b'hesam'

array([( 1234, b'hesam'), ( 5678, b'Alire'), (91011, b'uvwxy')],
      dtype=[('num', '<i8'), ('key', 'S5')])

In [ ]:
##in alamat ke poshte i8 oftade ro search konid bebinid chie ??????????????? '<i8' barmigarde be tartibe gharar giri dar byte haye hafeze


In [4]:
#numpy.ndarray.tolist

x = np.uint32([1, 2, 3])
x_list = x.tolist()
x_list

[1, 2, 3]

In [6]:
#hala yeki mige bia az classe liste python estefade kon mesle zir va mibinim hamoon ro bargardoond
x_list2 = list(x)
x_list2

[np.uint32(1), np.uint32(2), np.uint32(3)]

In [8]:
print(x_list[0],x_list2[0]) ##mibinim ke baz ham tak take anaser dar har 2 ravesh yeki hastan

1 1


In [9]:
print(type(x_list[0]),type(x_list2[0]))
#ba gereftane type mibinim ke oon ke ba method tolist anjam shode az class int hast va ooni ke ba methode builtin list khode python anjam shode az class numpy.unit32
#hast yani hamoon chizi ke too voroodi taarif kardam pas tafavote in 2 ta dar type eleman haye dakheli hast
#


<class 'int'> <class 'numpy.uint32'>


In [10]:
x_new = np.array([[1, 2], [3, 4]])##inja yek arrayeye  2D taarif mikonam
print(list(x_new), x_new.tolist())
##vaghti az list estefadeh mikonam oomade yek listi sakhte va har kodoom az anaser ro az array estefadeh karde vali yani be halate recursive nayoomade va har kodoom
#az inha ro list kone va oomade az array dar numpy estefadeh karde vali vaghti az tolist estefadeh mikonam in modeli mishe

[array([1, 2]), array([3, 4])] [[1, 2], [3, 4]]
