In [ ]:
###numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0,
#                   converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None,
#                   deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True,
#                   defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True,
#                   max_rows=None, encoding=None, *, ndmin=0, like=None)

In [ ]:
###ghesmate akhare I/O ro bebinim ke faghat genfromtxt moonde

#### dar in bakhsh be jaye inke yek file besazam miam va az yek technique jadid estefadeh mikonam .
#man vaghti file misazam in tooye disk man zakhire mishe va vahgti file ro mikhoonam miad tooye memory va bad man az rooye data ye tooye memory ro mikhoonam ya minevisam vali mikham inja be jaye inke
# data ro tooye hard berizam yek object e besazam ke
# az noe I/O bashe va tooye memory bashe va in ro be disk montaghel nakonim va in serfan baraye in hast ke sorate karemoon bala tar bere


####va yek estefadeye dg ham dare va oon ine ke age yek API benevisam ke montazere file e object hast , mitoonam yek object e az oon I/O besazam va in hamoon kare file ro mikone , hala age voroodie man
#az type I/O bashe engar ke yek file ro behesh dadam

In [3]:
##avval import ha ro migazaram va io ham import mikonam
import numpy as np
from sys import getsizeof as size
import copy
import io

In [ ]:
#hala migam ke io.StringIO ro seda mizanam va voroodie in yek string hast
data = "1,2,3\n4,5,6"
io.StringIO(data) #voroodi ro midam be in yani data ro midam be in function va khroojie in yek class az io hast yani yek file , faghat be jaye inke tooye disk bashe , tooye memory hast va dastresi
#behesh sari tar hast
#alan age type begiram in ro mibinam
print(type(data),type(io.StringIO(data))) ##mibinim ke type data az noe string hast va type io.StringIO(data) az noe voroodi khoroojie io hast


<class 'str'> <class '_io.StringIO'>


In [ ]:
#pas man az inja be baad miam va kole 'io.StringIO(data)' ro be onvane voroodi midam be genfromtxt be onvane file ya hamoon fname

# hala oon chizi ke mikham tooye file benevisam , ro tooye in data ba formate string minevisam va midam be StringIO()
#deleimiter moshakhas mikone ke joda konandeye data ma ke dar 'data' bala minevisim chi bashe ke default esh None ya hamoon whitespace hast
#masalan age 'data1' ro datash ro ba semicolon joda konam intori mishe

data1 = "1;2;3\n4;5;6"
#hala khoroojie io.StringIO(data1) ro midim be 'genfromtxt' va khorooji behem yek arrayeye 2 bodi mide
np.genfromtxt(io.StringIO(data1), delimiter= ";")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
###mitoonam be delimiter adad ham bedam ke in be in manie ke mikham joda konande ro bar asase tedade character dar nazar begiram
#yani dare mesale zir ba delimiter 2 avvalin character mishe '1;' va badi mishe '2;' va badi ham mishe '3' chon dg badesh newline khorde va edamash mohem nist va khodesho mindaze va 6 ham hamintor
#vali tooye khorooji mibinim ke '1;' va '2;' ro naneveshte cho dar damaneye data type taarif nashode , midoonim ke damaneye default numpy float hast va chon '1;' float nist 'nan' type mikone ke
# mitoonid error hesab konid
data1 = "1;2;3\n4;5;6"
np.genfromtxt(io.StringIO(data1), delimiter= 2)

array([[nan, nan,  3.],
       [nan, nan,  6.]])

In [ ]:
##age bekham moshkele bala ro hal konam beyen data space migzaram va be genfromtxt mifahmoonam ke '1 ' , 2 character hesab mishe
#va nokte ham ine ke character ' ' ya space ro ghabl ya bade adad ignore mikone va khode adad ro minevise vali character haye dg ro nemifahme va error ya nan type mikone
data2 = "1 2 3\n4 5 6"
np.genfromtxt(io.StringIO(data2), delimiter= 2)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
##hala age delimiter ro begzarim 3 miad va '1 2' ro dar nazar migire vali chon baz float nist ino nemifahme ke 12 hast va nan migzare va baraye '4 5' ham hamintor vali ' 3pooch' va ' 6pooch' ro mifahme
data2 = "1 2 3\n4 5 6"
np.genfromtxt(io.StringIO(data2), delimiter= 3)

#pas man vaghti 2 ta ragham dashte basham va beyne inha characte rhayi mesle space ya ; ya , ya ... bashe ino be onvane float nemifahme va nemifahme va nan migzare

array([[nan,  3.],
       [nan,  6.]])

In [ ]:
data2 = "142 3\n425 6"
np.genfromtxt(io.StringIO(data2), delimiter= 3)

array([[142.,   3.],
       [425.,   6.]])

In [ ]:
###hata shoma mitooni begi har sotoon chand character bashe ke dar mesale zir migam sotoone avval 2 character va sotoone dovom 3 character ke dar sotoone dovom '2 3' va '5 6' ba nan movajeh mishe
data2 = "142 3\n425 6"
np.genfromtxt(io.StringIO(data2), delimiter= (2, 3))

array([[14., nan],
       [42., nan]])

In [ ]:
data2 = "142 3\n425 6"
np.genfromtxt(io.StringIO(data2), delimiter= (2, 2)) ##inja miad va '2 ' ro 2 dar nazar migire va '5 ' ro 5 dar nazar migire

array([[14.,  2.],
       [42.,  5.]])

In [ ]:
##ma dar genfromtxt yek option e autostrip darim ke bahash migim bia va space haye ghabl va baade oon item haro hazf kon
data3 = "1, zxc , 2\n 2, vvv , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",", dtype="S5", autostrip=False)#inja hatman bayad datatype e ma string bashe chon age bekham data haro strip konam hatman bayad data haro be halate string dar
#biare ke betoone strip kone pas dtype ro S5 migzaram va 5 ham hamoon length string hast ke daram behesh midam va dar khorooji mibinim ke autostrip Flase hast pas space ha ham dar khorooji neshan
#dadeh mishe

array([[b'1', b' zxc ', b' 2'],
       [b'2', b' vvv ', b' 4']], dtype='|S5')

In [ ]:
np.genfromtxt(io.StringIO(data3), delimiter=",", dtype="S5", autostrip=True) ##hala age autostrip ro True konam dg space haro nemiare va hazfeshoon mikone

array([[b'1', b'zxc', b'2'],
       [b'2', b'vvv', b'4']], dtype='|S5')

In [ ]:
##hala age dtype ro int begzaram be jaye 'zxc' va 'vvv' migzare -1 ke in -1 yejoorayi yani hamoon 'nan' chon in 2 string hastan va mikhad be formate integer behesh negah kone va nemifahme
data3 = "1, zxc , 2\n 2, vvv , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",", dtype=int, autostrip=True)

array([[ 1, -1,  2],
       [ 2, -1,  4]])

In [ ]:
##nokte inke bala goftim string faghat ba string hamkhani dare pas age be jaye 'zxc' va 'vvv' , adad begzaram ham va ba  autostrip=True ya False khorooji ro begiram yeki hastan
data3 = "1, 3 , 2\n 2, 34 , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",", dtype=int, autostrip=False)

array([[ 1,  3,  2],
       [ 2, 34,  4]])

In [ ]:
data3 = "1, 3 , 2\n 2, 34 , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",", dtype=int, autostrip=True)

array([[ 1,  3,  2],
       [ 2, 34,  4]])

In [ ]:
###optione badi ke dar genfromtxt darim comments hast ke vaghti ma yek datasource e darim yek comment e minevisim ke tozih midan in data chie
data4 = """
#I am a comment
#I am a comment too
1, 2
3, 4
5, 6 #I am a comment at the end of the line
"""
np.genfromtxt(io.StringIO(data4), delimiter=",",  comments="#")


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
data4 = """
$I am a comment
$I am a comment too
1, 2
3, 4
5, 6 $I am a comment at the end of the line
"""
np.genfromtxt(io.StringIO(data4), delimiter=",",  comments="$")

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
###optione badi ke dar genfromtxt darim skip_header va skip_footer hast ke skip header mige az bala chand khat ro jump kon va skip footer mige az payi nchand khat ro jump kon
data4 = """
#I am a comment
#I am a comment too
1, 2
3, 4
5, 6 #I am a comment at the end of the line
"""
np.genfromtxt(io.StringIO(data4), delimiter=",",  comments="#", skip_header=4) # chon 4 khat ro az bala jump karde pas khate 1,2 ro ham hazf kard


array([[3., 4.],
       [5., 6.]])

In [ ]:
data4 = """
#I am a comment
#I am a comment too
1, 2
3, 4
5, 6 #I am a comment at the end of the line
"""
np.genfromtxt(io.StringIO(data4), delimiter=",",  comments="#", skip_header=4, skip_footer=1) #ba skip_footer khate 5,6 ro ham hazf kard

array([3., 4.])

In [ ]:
###optione badi ke dar genfromtxt darim usecols hast ke mige che sotoonhayi dar mohasebate feli dar nazar gerefte beshe masalan dar dataset bala mikham begam subject va weight ro dar nazar begire
#va baghye ro load nakone

data3 = "1, 3 , 2\n 2, 34 , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",",  usecols=(0, 1)) #dar khorooji mibinim ke sotoone akhar ro lahaz nakarde

array([[ 1.,  3.],
       [ 2., 34.]])

In [ ]:
data3 = "1, 3 , 2\n 2, 34 , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",",  usecols=(0, -1)) #hala age too in halat biam va indexe -1 ro bedam yani az samte rast shoroo be andis gozari kon ke avvali az rast mishe -1 va
#dovomi mishe -2 va .... pas alan andise 0 mishe  sotoone avval az chap va -1 mishe sotoone avval az rast va sotoone vasat ro nadade


array([[1., 2.],
       [2., 4.]])

In [4]:
##mitoonam be jaye inke ba andis kar konam az names estefadeh konam
data3 = "1, 3 , 2\n 2, 34 , 4"
np.genfromtxt(io.StringIO(data3), delimiter=",", names = "a, b, c" , usecols=("a", "c"))

array([(1., 2.), (2., 4.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [5]:
##yek raveshe dg baraye dadane name be sotoon ha be raveshe zir hast
data4 = "1 2 3\n 4 5 6"
np.genfromtxt(io.StringIO(data4), dtype= [(_,int) for _ in "abc"])  #inja ke maloome _ yani variable e ke mikham name khasi nadashte bashe
#inja oomadam va datatype ro barabar ba yek listi gharar dadam ke be har sotoon type int dadam
#vaghti az yek list estefadeh mikonam va int ro be onvane type midam yani har sotoon ro mikham int taarif konam vali vaghti miam va migam in "abc" in motevajeh mishe ke man daram be sotoon ha name midam
#pas in mifahme ke daram migam be sotoon ha name bede va be har kodoom az sotoon ha be onvane type int bede

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [ ]:
##ya hata mitoonam inja kheyli rasmi begam esme in sotoon ha "abc" hast
data4 = "1 2 3\n 4 5 6"
np.genfromtxt(io.StringIO(data4), names = "a, b, c", dtype= [(_,int) for _ in "abc"])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [6]:
##age man data e be shekle zir dashte basham va inja mikham begam ke in a,b,c ke be onvane comment dar nazar gerefti be onvane name in column ha dar nazar begir????
#tanha kari ke bayad anjam bedam ine ke begam names ro True kon
#age inkaro anjam bedam , age man comment too neveshte ha dashte basham va names ham True bashe oon comment ro be onvane name column ha dar nazar migire


data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), names = True)

#ino ejra kardam va error khord chera??? dalilesh ine ke chon string daram (salam) va yek seri ham data adadi daram mige man ino ba formate float nemifahmam
#pas miam khate avval ro skip mikonam ke hamoon string bashe

ValueError: Some errors were detected !
    Line #3 (got 3 columns instead of 1)
    Line #4 (got 3 columns instead of 1)

In [ ]:
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1, names = True)  ##va mibinim ke formate hameye inha f8 ya float hast

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [7]:
##ma yek option e defaultfmt ya defaultformat darim ke miad va olgooyi baraye name dadan be column ha be soorate pishfarz dar nazar migire ke %i yani az 0 beshmor boro jolo va f%i
#yani sotoon haro intori namgozari mikone  f0 , f1 ,f2 ...

#masalan dar mesale ghabli names ro bar midaram ke baes mishe name sotoon ro baramoon nanevise
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1, dtype=(int, float, int)) ##Mibinim ke esme sotoon ha too khorooji f0, f1 va f2 hast ke az hamoon default fmt peyravi mikone

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<i8')])

In [8]:
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1, dtype=(int, float, int), names = "a") ##hala age names = "a" ro be bala ezafe konam miad va esme sotoone avval ro "a" migzare vali esme baghye sotoon
#haro az hamoon naming default fmt estefadeh mikone

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('a', '<i8'), ('f0', '<f8'), ('f1', '<i8')])

In [ ]:
##hala age bekham baraye name sotoon ha az pattern khasi estefadeh konam intori minevisam
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1, dtype=(int, float, int), names = "var_%2d")
#mibinim baz faghat esme sotoone aval ro kard var_2d va baghye sotoon ha az hamoon default format estefadeh mikonan

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_2d', '<i8'), ('f0', '<f8'), ('f1', '<i8')])

In [9]:
#pas bayad biam dar bala be jaye names az defaultfmt estefadeh konam
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1, dtype=(int, float, int), defaultfmt = "var_%2d")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_ 0', '<i8'), ('var_ 1', '<f8'), ('var_ 2', '<i8')])

In [ ]:
##Mitoonam yek 0 ham ghable 2d begzaram ke esme sotoon haro 2 raghami dar nazar begire va age adadi 1 raghami bood , yek 0 ghablesh mindaze vali masalan be 10 berese dg 0 ghablesh nemindaze
data5 = "salam \n #a b c\n 1 2 3 \n 4 5 6"
np.genfromtxt(io.StringIO(data5), skip_header=1, dtype=(int, float, int), defaultfmt = "var_%02d")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_00', '<i8'), ('var_01', '<f8'), ('var_02', '<i8')])

# Most Important
1-Missing values
2-bad format data

In [ ]:
###masalan too data zir ma missing value dashtim ke dar mesale loadtxt oomadim yek fnction neveshtim ke inaro ok kone
#inja yek option baraye missing_values darim va yek option ham baraye badformats darim ke option e  converter ha hastan ke in converter ha hamoona  hastan ke too loadtxt estefadeh kardim

In [19]:
#example for badformat data
#farz konid man data6 ro be in shekl daram ke yek seri % ham dare va vaghti ino be genfromtxt midam oon adad haye % dar ro baram nan neshoon mide chon mige man character e % ro nemifahmam tooye
#float chon defaukt man float hast
data6 = "1, 2.3%, 56.\n 7, 89.99%, 0"
np.genfromtxt(io.StringIO(data6), delimiter=",")
#pas bayad biam correction bezanam va % ro mafhoome riazish ro piadeh konam masalan 2.3% mishe 2.3/100

array([[ 1., nan, 56.],
       [ 7., nan,  0.]])

In [16]:
##pas b a lambda yek function minevisam ke alamate % ro strip mikone va baad taghsim be 100 mikone
data6 = "1, 2.3%, 56.\n 7, 89.99%, 0"
convertor = lambda x :float(x.strip("%"))/100.
np.genfromtxt(io.StringIO(data6), delimiter=",", converters={1:convertor})  ##hala miam va in converters ro rooye sotoone avval emal mikonam


array([[1.000e+00, 2.300e-02, 5.600e+01],
       [7.000e+00, 8.999e-01, 0.000e+00]])

In [18]:
##faghat oomade ba namade elmi neshoonesh dadeh pas baraye dorost kardanesh az names estefadeh mikonim
data6 = "1, 2.3%, 56.\n 7, 89.99%, 0"
convertor = lambda x :float(x.strip("%"))/100.
np.genfromtxt(io.StringIO(data6), delimiter=",", converters={1:convertor}, names = "A, B, C")

#in badformat data ro ba excel va notepad++ mishe dorostesh kard chon notepad++ regex dare

array([(1., 0.023 , 56.), (7., 0.8999,  0.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [25]:
#example for missing data
#yek convertor minevisam ke chrarctere khali ro strip kon(vaghti too strip hichi nagzaram yani charactere khali ro strip kon) ya be jash manfie 1000 begzar chon age
#jaye khali bashe error migire va mige jaye khali ba formate float nemikhoone va adad mikham
data7 = "1, ,3\n5, 6, 7"
convertor = lambda x :float(x.strip() or -1000)
np.genfromtxt(io.StringIO(data7), delimiter=",", converters={1:convertor}, names = "A, B, C")

array([(1., -1000., 3.), (5.,     6., 7.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [23]:
###hala negah konim age intori benevisim chi mishe ???
data7 = "1, ,3\n5, 6, 7"
convertor = lambda x :float(-1000)
np.genfromtxt(io.StringIO(data7), delimiter=",", converters={1:convertor}, names = "A, B, C")

##mibinim ke jaye sotoone avval kolan -1000 gozasht ke khoob nist yani 6 ro ham ba -1000 replace kard pas x.strip kari ke too code mikone ine ke space ghable 6 ro mizane va mibine ke adad dare pas ba
#-1000 replace nemikone pas ya strip mikone va age adad bashe chizi bar nemigardoone ya age kolan space bashe -1000 jash migzare

array([(1., -1000., 3.), (5., -1000., 7.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [24]:
#example for missing data
data8 = "N/A, 2, 3\n4, ,???" ###N/A yani not available va jaye khali va ??? har 3 ta missing data ma hastan
kwargs = dict(delimiter=",",
               dtype=int,
               names="A, B, C",
               missing_values={0:"N/A", "B":" ", 2:"???" }, ###inja goftam ke too sotoone aval "N/A" hast tooye sotoone dovom space ya fazaye khali hast ke hala man ham mitoonam be jaye sotoone
               #dovvom 1 begzaram va begam charactere space yani : 1:" " ham mitoonam esme sotoone dovom ro bedam : "B":" " yani esme sotoon ro ke bala taarif kardim gharar bedam
               #va tooye sotoone sevom ham ke charactere missed shodeye man ??? hast
               filling_values={0: 10,'B': 9, 2:-100 }  ###hala inja migam ke oon missing values ro ba chi por kone
               )
np.genfromtxt(io.StringIO(data8), **kwargs) ###inja be jaye inke tak tak parameter haro gharar bedam miam va kwargs ro taarif mikonam va kwargs ro be onvane yek dictionary taarif mikonam

array([(10, 2,    3), ( 4, 9, -100)],
      dtype=[('A', '<i8'), ('B', '<i8'), ('C', '<i8')])

In [27]:
#man mitoonam yek tuple az mfilling values taarif konam va begam boro ino tooye jahaye khalie data insert kon
####example for missing data
data9 = """
1,2,,,5
6,,7,,
10,,,,
"""
filling_values = (100, 200, 300, 400, 500) ##intori vaghti taarif mikonam yani boro too sotoone avval begard va harja khali bood 100 begzar va too sotoone dovom begard har ja khali bood 200 bezar va ...
np.genfromtxt(io.StringIO(data9), delimiter=",", filling_values=filling_values)


array([[  1.,   2., 300., 400.,   5.],
       [  6., 200.,   7., 400., 500.],
       [ 10., 200., 300., 400., 500.]])